[URLS]
tibiaPageUrl=http://127.0.0.1/
tibiaStoreGetCoinsUrl=http://127.0.0.1//donate
getPremiumUrl=http://127.0.0.1//donate
createAccountUrl=http://127.0.0.1//cadastro
accessAccountUrl=http://127.0.0.1/
lostAccountUrl=http://127.0.0.1/
manualUrl=http://127.0.0.1/
faqUrl=http://127.0.0.1//wiki
premiumFeaturesUrl=http://127.0.0.1/
limesurveyUrl=http://127.0.0.1/
hintsUrl=http://127.0.0.1//hints.json
cipSoftUrl=http://127.0.0.1
twitchTibiaUrl=https://www.twitch.tv/directory/game/Tibia
youTubeTibiaUrl=https://youtube.com
crashReportUrl=http://127.0.0.1/
fpsHistoryRecipient=http://127.0.0.1/
tutorialProgressWebService=http://127.0.0.1/
wheelOfDestinyPlannerDirectUrl=https://www.tibia.com/community/?subtopic=wheelofdestinyplanner&code=
loginWebService=http://127.0.0.1/login.php
clientWebService=http://127.0.0.1/login.php
accountCreationClientServices=http://127.0.0.1/login.php
accountCreationClientServicesRecaptchaV2Content=https://www.tibia.com/clientservices/recaptcha_v2_content.php
accountCreationClientServicesRecaptchaV3Content=https://www.tibia.com/clientservices/recaptcha_v3_content.php

[GRAPHICS]
; keep spritesheetCacheSize commented so that the automatic cache size mechanism becomes active
;spritesheetCacheSize=350
qsgAtlasWidth=4096
qsgAtlasHeight=4096
maximumNumberOfEffects=400
missileFlyDelayMsec=150
numericalEffectDisplayDurationMsec=1000 
numericalEffectMergeDurationMsec=100
temporaryMarkDisplayDurationMsec=1000 
renderLoopType=threaded

[FPSHISTORY]
sampleRateMsec=30000
uploadRateSec=300

[NETWORK]
maxConcurrentDownloads=5

[MOVEMENT]
minPercentageOfCurrentMovementBeforeSendNext=1.0
maxMillisecondsToFinishCurrentMovementBeforeSendNext=0

[CHAT]
maxChatBacklogLength=1000
maxChatInputHistoryLength=1000

[SOUND]
failInitialization=false
numberOfSoundStreams=64
playableSoundDataCachingTimeInSeconds=60
fadeSteps=100
ambienceStreamFadeDuration=1000
ambienceObjectStreamFadeDuration=500
distanceFadePerStep=10
distanceFadeBase=100
distanceModifierForZ=3
musicFadeDuration=2000
musicMaxSecondsPlaying=0
musicRandomDelayFirstTrackSeconds=10-120
musicRandomDelayNextTrackSeconds=120-600
musicRandomDelayEarliestRepetitionInSeconds=600-1200
musicRandomDelayEarliestRepetitionForImmediateInSeconds=60-180
distanceAttackImpactDelay=250
disableAmbienceStreams=false
disableAmbienceObjectSounds=false
